<a href="https://colab.research.google.com/github/tiffanymtang/cs294-final-project/blob/main/deepSEA_starter_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Activate env and import packages

In [ ]:
# Go to  Kernel -> Change Kernel -> Choose kipoi-DeepSEA__predict

In [1]:
import numpy as np
import kipoi

### Load model and make a sample prediction

In [ ]:
model = kipoi.get_model('DeepSEA/predict')
pred = model.pipeline.predict_example() # make a sample prediction

In [3]:
print('Making a sample prediction...')
print(pred)

Making a sample prediction...
[[0.08160981 0.06867644 0.10076747 ... 0.0949342  0.0213389  0.01201444]
 [0.06698146 0.01062419 0.02694622 ... 0.1549085  0.04822358 0.00770115]
 [0.04445553 0.00539729 0.01840801 ... 0.14994659 0.35297102 0.02272808]
 ...
 [0.0008136  0.00404319 0.00176919 ... 0.02167323 0.11304315 0.02273135]
 [0.00079005 0.00249488 0.00252156 ... 0.05105033 0.04735982 0.01576872]
 [0.00076794 0.00237441 0.00250101 ... 0.05096884 0.04723744 0.0151526 ]]
